#!/usr/bin/env node
/**
 * Generate per-glyph advance-width table from Inter font using fontkit.
 * 
 * Usage:
 *   node tools/fonts/extract-metrics.js <font-file-path> [output-path]
 * 
 * Example:
 *   node tools/fonts/extract-metrics.js examples/nextjs-sample/public/fonts/Inter-Regular.ttf \
 *     packages/tldraw/src/blocks/layout/inter-generated.ts
 */

const fs = require('fs')
const path = require('path')

// Try to load fontkit
let fontkit
try {
  fontkit = require('fontkit')
} catch (e) {
  console.error(`
Error: fontkit is required but not installed.

Install it with:
  npm install -g fontkit
  or use a font tools package
`)
  process.exit(1)
}

// Characters to include in the output table
const TARGET_CHARS = new Set([
  // A-Z
  ...Array.from({ length: 26 }, (_, i) => String.fromCharCode(65 + i)),
  // a-z
  ...Array.from({ length: 26 }, (_, i) => String.fromCharCode(97 + i)),
  // 0-9
  ...Array.from({ length: 10 }, (_, i) => String.fromCharCode(48 + i)),
  // Punctuation and symbols
  '.', ',', ':', ';', '!', '?', "'", '"', '-', '–', '—', '(', ')', '[', ']', '{', '}',
  '/', '\\', '@', '#', '$', '%', '&', '*', '+', '=', '<', '>', '~', '^', '_', '|', '`',
  // Space
  ' ',
])

// Sort characters for consistent output
const SORTED_CHARS = Array.from(TARGET_CHARS).sort()

function generateMetricsTable(font, fontName = 'generated') {
  const unitsPerEm = font.unitsPerEm || 1000
  
  const chars = {}
  
  for (const char of SORTED_CHARS) {
    const glyph = font.charToGlyph(char)
    const width = glyph.advanceWidth || 0
    chars[char] = Math.round((width / unitsPerEm) * 10000) / 10000
  }
  
  // Calculate average width for default
  const widths = Object.values(chars)
  const avgWidth = widths.reduce((a, b) => a + b, 0) / widths.length
  
  return {
    default: avgWidth,
    chars,
  }
}

function escapeChar(str) {
  switch (str) {
    case "'":
      return "\\'"
    case '"':
      return '\\"'
    case '\\':
      return '\\\\'
    default:
      return str
  }
}

function formatTable(table, indent = '  ') {
  const lines = []
  
  lines.push(`  default: ${table.default.toFixed(2)},`)
  lines.push('  chars: {')
  
  const chars = table.chars
  const entries = Object.entries(chars).sort(([a], [b]) => a.localeCompare(b))
  
  for (const [char, width] of entries) {
    const escaped = escapeChar(char)
    lines.push(`      ${JSON.stringify(escaped)}: ${width.toFixed(2)},`)
  }
  
  lines.push('    },')
  return lines.join('\n')
}

function generateTypeScriptFile(fontName, tables, fontPath, fontVersion) {
  const header = `/**
 * Auto-generated from ${fontName} font.
 * Source: ${fontPath}
 * Generated by: tools/fonts/extract-metrics.js (using fontkit)
 * 
 * DO NOT EDIT MANUALLY. This file is regenerated from font binaries.
 * Version: ${fontVersion}
 */

export const ADVANCE_WIDTH_TABLES = {
${formatTable(tables)}
}`

  return header
}

function main() {
  const args = process.argv.slice(2)
  
  if (args.length < 1) {
    console.error('Usage: node tools/fonts/extract-metrics.js <font-file-path> [output-path]')
    process.exit(1)
  }
  
  const fontPath = args[0]
  const outputPath = args[1] || 'packages/tldraw/src/blocks/layout/inter-generated.ts'
  
  if (!fs.existsSync(fontPath)) {
    console.error(`Error: Font file not found: ${fontPath}`)
    process.exit(1)
  }
  
  console.log(`Reading font from: ${fontPath}`)
  
  const font = fontkit.openSync(fontPath)
  
  if (!font) {
    console.error('Error: Could not open font file')
    process.exit(1)
  }
  
  const fontName = font.names.fullName?.en || font.names.fontFamily?.en || 'Unknown'
  const fontVersion = font.names.version?.en || 'unknown'
  
  console.log(`Font: ${fontName}`)
  console.log(`Version: ${fontVersion}`)
  console.log(`Units per EM: ${font.unitsPerEm}`)
  
  const interTable = generateMetricsTable(font, 'inter')
  
  const output = generateTypeScriptFile(
    'Inter',
    { default: interTable.default, chars: interTable.chars },
    fontPath,
    fontVersion
  )
  
  // Write output file
  const fullOutputPath = path.resolve(process.cwd(), outputPath)
  const dir = path.dirname(fullOutputPath)
  
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true })
  }
  
  fs.writeFileSync(fullOutputPath, output)
  console.log(`\nGenerated metrics table written to: ${fullOutputPath}`)
  
  // Print sample widths
  console.log(`\nSample character widths (in em units):`)
  console.log(`  'm': ${interTable.chars['m']}`)
  console.log(`  'n': ${interTable.chars['n']}`)
  console.log(`  'o': ${interTable.chars['o']}`)
  console.log(`  'i': ${interTable.chars['i']}`)
  console.log(`  'H': ${interTable.chars['H']}`)
  console.log(`  '1': ${interTable.chars['1']}`)
  console.log(`  '.': ${interTable.chars['.']}`)
  console.log(`  ' ': ${interTable.chars[' '] || 0}`)
}

if (require.main === module) {
  main()
}