#!/usr/bin/env node
/**
 * Generate per-glyph advance-width table from Inter font files.
 *
 * Usage:
 *   node tools/fonts/gen-metrics.js <font-file-path> [output-path]
 *
 * Example:
 *   node tools/fonts/gen-metrics.js assets/fonts/Inter-VariableFont_wght.ttf \
 *     packages/tldraw/src/blocks/layout/inter-generated.ts
 *
 * This script uses the opentype.js library to read glyph advance widths from
 * a font file and generates a TypeScript module with the per-character advance
 * width table for use in measure.ts.
 *
 * Requirements:
 *   - Font file must be a .ttf or .otf file (woff2 requires decompression first)
 *   - The font should be Inter Regular for accurate character width measurements
 *
 * Output format:
 *   - A TypeScript file exporting ADVANCE_WIDTH_TABLES with character -> width (em) mappings
 *   - Compatible with the tableMetrics provider in measure.ts
 *
 * NOTE: For production use, it's recommended to use fontkit or fonttools (Python)
 * for more accurate glyph extraction. This is a Node.js-based solution.
 */

const fs = require('fs')
const path = require('path')

// Try to load opentype.js
let opentype
try {
  opentype = require('opentype.js')
} catch (e) {
  console.error(`
Error: opentype.js is required but not installed.

Install it with:
  npm install opentype.js
  or
  yarn add opentype.js

For accurate font metrics, consider using Python's fonttools:
  pip install fonttools
  python tools/fonts/gen-metrics-py.py <font-file>

This script is a Node.js fallback using opentype.js.
`)
  process.exit(1)
}

// Characters to include in the output table
const TARGET_CHARS = new Set([
  // A-Z
  ...Array.from({ length: 26 }, (_, i) => String.fromCharCode(65 + i)),
  // a-z
  ...Array.from({ length: 26 }, (_, i) => String.fromCharCode(97 + i)),
  // 0-9
  ...Array.from({ length: 10 }, (_, i) => String.fromCharCode(48 + i)),
  // Punctuation and symbols
  '.', ',', ':', ';', '!', '?', "'", '"', '-', '–', '—', '(', ')', '[', ']', '{', '}',
  '/', '\\', '@', '#', '$', '%', '&', '*', '+', '=', '<', '>', '~', '^', '_', '|', '`',
  // Space
  ' ',
  // Additional common characters
  ' ', '!', '"', '#', '$', '%', '&', "'", '(', ')', '*', '+', ',', '-', '.', '/',
  ':', ';', '<', '=', '>', '?', '@',
  '[', '\\', ']', '^', '_', '`', '{', '|', '}', '~',
])

// Sort characters for consistent output
const SORTED_CHARS = Array.from(TARGET_CHARS).sort()

function generateMetricsTable(font, fontName = 'generated') {
  const unitsPerEm = font.unitsPerEm || 1000
  const defaultWidth = font.getGlyphForChar('H').advanceWidth || 500

  const chars = {}

  for (const char of SORTED_CHARS) {
    const code = char.charCodeAt(0)
    const glyph = font.charToGlyph(char)
    const width = (glyph.advanceWidth || defaultWidth) / unitsPerEm

    // Round to 4 decimal places for cleaner output
    chars[char] = Math.round(width * 10000) / 10000
  }

  // Calculate average width for default
  const widths = Object.values(chars)
  const avgWidth = widths.reduce((a, b) => a + b, 0) / widths.length

  return {
    default: avgWidth,
    chars,
  }
}

function escapeChar(str) {
  switch (str) {
    case "'":
      return "\\'"
    case '"':
      return '\\"'
    case '\\':
      return '\\\\'
    default:
      return str
  }
}

function formatTable(table, indent = '  ') {
  const lines = []

  lines.push(`  default: ${table.default.toFixed(2)},`)
  lines.push('  chars: {')

  const chars = table.chars
  const entries = Object.entries(chars).sort(([a], [b]) => a.localeCompare(b))

  for (const [char, width] of entries) {
    const escaped = escapeChar(char)
    lines.push(`      ${JSON.stringify(escaped)}: ${width.toFixed(2)},`)
  }

  lines.push('    },')
  return lines.join('\n')
}

function generateTypeScriptFile(fontName, tables, fontPath, fontVersion) {
  const header = `/**
 * Auto-generated from ${fontName} font.
 * Source: ${fontPath}
 * Generated by: tools/fonts/gen-metrics.js
 * 
 * DO NOT EDIT MANUALLY. This file is regenerated from font binaries.
 * Version: ${fontVersion}
 */

export const ADVANCE_WIDTH_TABLES = {
${formatTable(tables)}
}`

  return header
}

function main() {
  const args = process.argv.slice(2)

  if (args.length < 1) {
    console.error('Usage: node tools/fonts/gen-metrics.js <font-file-path> [output-path]')
    process.exit(1)
  }

  const fontPath = args[0]
  const outputPath = args[1] || 'packages/tldraw/src/blocks/layout/inter-generated.ts'

  if (!fs.existsSync(fontPath)) {
    console.error(`Error: Font file not found: ${fontPath}`)
    process.exit(1)
  }

  console.log(`Reading font from: ${fontPath}`)
  const font = opentype.load(fontPath)

  // Get font version from name table
  const fontVersion = font.names.unitsPerEm
    ? `unitsPerEm=${font.unitsPerEm}`
    : font.names.version?.en || 'unknown'

  console.log(`Font: ${font.names.fullName?.en || 'Unknown'}`)
  console.log(`Version: ${fontVersion}`)

  // Generate metrics for Inter font
  const interTable = generateMetricsTable(font, 'inter')

  const output = generateTypeScriptFile(
    'Inter',
    { default: interTable.default, chars: interTable.chars },
    fontPath,
    fontVersion
  )

  // Write output file
  const fullOutputPath = path.resolve(process.cwd(), outputPath)
  const dir = path.dirname(fullOutputPath)

  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true })
  }

  fs.writeFileSync(fullOutputPath, output)
  console.log(`\nGenerated metrics table written to: ${fullOutputPath}`)

  // Print sample widths
  console.log(`\nSample character widths (in em units):`)
  console.log(`  'm': ${interTable.chars['m']}`)
  console.log(`  'n': ${interTable.chars['n']}`)
  console.log(`  'o': ${interTable.chars['o']}`)
  console.log(`  'i': ${interTable.chars['i']}`)
  console.log(`  'H': ${interTable.chars['H']}`)
  console.log(`  '1': ${interTable.chars['1']}`)
  console.log(`  '.': ${interTable.chars['.']}`)
  console.log(`  ' ': ${interTable.chars[' '] || 0}`)
}

if (require.main === module) {
  main()
}