#!/usr/bin/env python3
"""
Generate per-glyph advance-width table from Inter font files using fonttools.

Usage:
    python tools/fonts/gen-metrics-py.py <font-file-path> [output-path]

Example:
    python tools/fonts/gen-metrics-py.py \
      assets/fonts/Inter-VariableFont_wght.ttf \
      packages/tldraw/src/blocks/layout/inter-generated.ts

This script uses fonttools (aDejaVuSans) to read glyph advance widths from
a font file and generates a TypeScript module with the per-character advance
width table for use in measure.ts.

Requirements:
    pip install fonttools

Output format:
    A TypeScript file exporting ADVANCE_WIDTH_TABLES with character -> width (em) mappings
    Compatible with the tableMetrics provider in measure.ts
"""

import sys
import os
from fontTools.ttLib import TTFont

# Characters to include in the output table
TARGET_CHARS = set()

# A-Z
for i in range(65, 91):
    TARGET_CHARS.add(chr(i))
# a-z
for i in range(97, 123):
    TARGET_CHARS.add(chr(i))
# 0-9
for i in range(48, 58):
    TARGET_CHARS.add(chr(i))
# Punctuation and symbols
for c in ".,:;'\"?!-–—()[]{}/@#$%&*+=<>`~^_|\\":
    TARGET_CHARS.add(c)
# Space
TARGET_CHARS.add(' ')

# Sort characters for consistent output
SORTED_CHARS = sorted(TARGET_CHARS)


def generate_metrics_table(font: TTFont, font_name: str = "generated") -> dict:
    """Generate advance-width table from font."""
    max_pem = font['hmtx'].metrics
    units_per_em = font['head'].unitsPerEm
    default_width = 500  # fallback

    chars = {}
    widths = []

    for char in SORTED_CHARS:
        glyph_name = font.getGlyphID(char)
        if glyph_name is not None:
            glyph_name = font['cmap'].getBestCmap().get(ord(char), None)
            if glyph_name is None:
                continue

            if glyph_name in max_pem:
                width = max_pem[glyph_name][0] / units_per_em
                chars[char] = round(width, 4)
                widths.append(width)
            else:
                # Use default width
                chars[char] = default_width / 1000
                widths.append(default_width / 1000)

    avg_width = sum(widths) / len(widths) if widths else 0.54

    return {
        "default": round(avg_width, 4),
        "chars": chars
    }


def format_table(table: dict, indent: str = "  ") -> list:
    """Format table as TypeScript object."""
    lines = []
    lines.append(f"  default: {table['default']},")
    lines.append("  chars: {")

    for char, width in sorted(table['chars'].items(), key=lambda x: x[0]):
        escaped = char.replace('\\', '\\\\').replace("'", "\\'")
        lines.append(f"      '{escaped}': {width},")

    lines.append("    },")
    return lines


def generate_typescript_file(font_name: str, tables: dict, font_path: str, font_version: str) -> str:
    """Generate complete TypeScript file content."""
    table_lines = format_table(tables)
    table_content = "\n".join(table_lines)

    header = f"""/**
 * Auto-generated from {font_name} font.
 * Source: {font_path}
 * Generated by: tools/fonts/gen-metrics-py.py
 *
 * DO NOT EDIT MANUALLY. This file is regenerated from font binaries.
 * Version: {font_version}
 */

export const ADVANCE_WIDTH_TABLES = {{
{table_content}
}}
"""
    return header


def main():
    if len(sys.argv) < 2:
        print("Usage: python tools/fonts/gen-metrics-py.py <font-file-path> [output-path]")
        sys.exit(1)

    font_path = sys.argv[1]
    output_path = sys.argv[2] if len(sys.argv) > 2 else "packages/tldraw/src/blocks/layout/inter-generated.ts"

    if not os.path.exists(font_path):
        print(f"Error: Font file not found: {font_path}")
        sys.exit(1)

    print(f"Reading font from: {font_path}")
    font = TTFont(font_path)

    # Get font metadata
    font_name = "Inter"
    font_version = "unknown"

    try:
        name_table = font['name']
        full_name = name_table.getBestFamilyName() or name_table.getBestFullName() or "Unknown"
        version = name_table.getBestVersion() or "unknown"

        if full_name:
            font_name = full_name
        if version:
            font_version = str(version)

        print(f"Font: {font_name}")
        print(f"Version: {font_version}")
    except Exception as e:
        print(f"Warning: Could not read font metadata: {e}")

    # Generate metrics table
    inter_table = generate_metrics_table(font, "inter")

    output = generate_typescript_file(
        font_name,
        {"default": inter_table["default"], "chars": inter_table["chars"]},
        font_path,
        font_version
    )

    # Write output file
    output_path = os.path.abspath(output_path)
    dir_path = os.path.dirname(output_path)

    if not os.path.exists(dir_path):
        os.makedirs(dir_path, exist_ok=True)

    with open(output_path, 'w') as f:
        f.write(output)

    print(f"\nGenerated metrics table written to: {output_path}")

    # Print sample widths
    print(f"\nSample character widths (in em units):")
    print(f"  'm': {inter_table['chars'].get('m', 'N/A')}")
    print(f"  'n': {inter_table['chars'].get('n', 'N/A')}")
    print(f"  'o': {inter_table['chars'].get('o', 'N/A')}")
    print(f"  'i': {inter_table['chars'].get('i', 'N/A')}")
    print(f"  'H': {inter_table['chars'].get('H', 'N/A')}")
    print(f"  '1': {inter_table['chars'].get('1', 'N/A')}")
    print(f"  '.': {inter_table['chars'].get('.', 'N/A')}")
    print(f"  ' ': {inter_table['chars'].get(' ', 0)}")


if __name__ == "__main__":
    main()