/**
 * Inter kerning pairs (em, grouped by value), measured in headless Chromium with `canvas.measureText`
 * against the Inter the Next.js sample serves (`next/font`, OFL-1.1): `w(ab) - w(a) - w(b)` at 400 for
 * every pair of visible ASCII glyphs, stored when ≥ 0.005 em, rounded to 0.005 em.
 * GENERATED by `tools/layout-report/calibrate/font-widths.js` — do not edit; re-run it instead.
 */

export const INTER_KERN: Record<string, string> = {
    "-0.37": "=>",
    "-0.17": "-><-",
    "-0.165": "\"J'J",
    "-0.16": "7_",
    "-0.135": "*,*.^,^.",
    "-0.13": "L^",
    "-0.125": "7,7.",
    "-0.11": "7AK+K-K~_1",
    "-0.1": "Tt",
    "-0.095": "7J=YLTPJV,V.VJW,W.Y=^J",
    "-0.09": ",?.?FAL\"L'TJ",
    "-0.085": ",1.1ATL+L-L~TAbYcYeYk<oYpY",
    "-0.08": "\",\".\"A','.'A+Y,\",'-Y.\".'A\"A'A^T7TcTdTeTgToTqV_Y+Y-Y~\\\"\\'\\*\\^^A_V_\\_v_ybTcTeToTpTv_y_~Y",
    "-0.075": "&Y+T-T>\\AYPAT+T-TaTsTuT~YAYcYdYeYgYoYq\\YaYhYmYnYsTsYw,w.~T",
    "-0.07": "*_=V=\\AVA\\AvAwAyFJLVL\\LvLyT4VAY4YaYs\\w^__*_^aThTmTnTvAwAyA",
    "-0.06": "74\"4&V&\\'4/J:\\;V;\\=W?AA?KwTvTwTxTyV:V;V=W=WJY&Y:Y;\\?f4fJr,r.vJxTyJ",
    "-0.055": "&T7#AWBTJ/T_TmTnTpTrU/WAXa\\W_4_Tf,f.kTrJrTuYv/wJy/",
    "-0.05": "+V+W+\\-V-W-\\7c7d7e7g7m7n7o7p7q7r=A=XA=J_T/U_V&V+V-V/VaVcVdVeVgVoVqV~W&W+W-W:W;WaWcWdWeWgWoWqW~X=\\=\\V\\\\\\v\\yaVaWa\\bVbWb\\cVcWc\\eVeWe\\gThVhWh\\mVmWm\\nVnWn\\oVoWo\\pVpWp\\qTuTwT~V~W~\\",
    "-0.045": "+J,@,C,G,O,Q-J.@.C.G.O.Q0_6_7&7a9_=T@,@.D,D.L1O,O.P+P-P~Q,Q.TzVs^4_0_3_5_6_8_9k+k-k4k~sVs\\v,v.y,y.~J",
    "-0.04": "&W/,/.7s=v=y@/@_C_D/D_F,FcFdFeFgFoFqKcKdKeKgKoKqKvKyO/O_P,Q/Q_T:X4XTYmYnYpYrYuZ+Z-Z~\\T_@_C_G_O_Q_Ua1ffh1m1n1r+r-r<rAr~u+u-u<u~v+v-v=v~y+y-y=y~",
    "-0.035": "\"&&\"&'&v&w&y'&+2+A+X,T,Y-2-A-X.T.Y0X0Y4,4.6,6.7:7;9X9Y;T=x@\\A+A-A1ACAGAOAQA~DADVDXDYD\\F.F_FuFvFyFzJ,J.K=KCKGKOKQKuLYOAOVOXOYO\\P&P.QAQVQXQYQ\\T&T,T.T0T6T;T=U,U.V4VCVGVOVQW4WmWnWpWrWsX+X-X0X6XCXGXOXQX~Y,Y.YCYGYJYOYQZCZGZOZQ\\+\\-\\1\\@\\C\\G\\O\\Q\\~^&b1bAc1cAe1eAfAfto1oAp1pAr/rZsWtTu/u_v<vTvYw&wZx=y<yTyYzT~2~A~X",
    "-0.03": "DTFmFnFpFrGTLCLGLOLQOTQTTCTGTOTQXcXdXeXgXoXqYibXcXeXf+f-f/fcfdfefgfofqf~oXpXt<",
    "-0.025": ",0,3,6.0.3.6/A0,0.5,5.9,9.FaRYtf",
    "-0.02": "4197+7+x,8-7-x.8073,3.3X4^8,8.8XAUAtCAGAGVGYG\\JALtUAX3X8\\U\\tbvbwbxbycvcwcxcyevewexeyfskckdkekgkokqovowoxoypvpwpxpyt+t-t~vcvdvevgvovqwcwdwewgwowqx+x-xcxdxexgxoxqx~ycydyeygyoyq~7~x",
    "-0.015": "2470737678\"c\"d\"e\"g\"o\"q'c'd'e'g'o'q,5,7.5.73^8^RVR\\RcRdReRgRoRqavayb\"b'bzc\"c'cze\"e'ezf_fahvhymvmynvnyo\"o'ozp\"p'pzrcrdrergrorqt4tYzczdzezgzozq",
    "-0.01": "7579$X(c(d(e(g(o(q*@+3-30V0\\9V9\\K$KSSXV0V6X$XS[c[d[e[g[o[q^@^C^G^O^Qb)b]b}c)c]c}e)e]e}o)o]o}p)p]p}tVtWt\\tctdtetgtotqts{c{d{e{g{o{q~3",
    "-0.005": "$T,9.9CXGXPcPdPePgPoPqRaSTvaya",
    "0.005": "1v1yAiHvHyIvIyMvMyNvNy\\idvdylvlytavBvDvEvFvHvIvKvLvMvNvPvRvbvhvkvlv|yByDyEyFyHyIyKyLyMyNyPyRybyhykyly||v|y",
    "0.01": "bacaeafYoaparirwtj",
    "0.015": "0t1t9tAAHtItKiMtNtVVV\\\\AdtfwltrBrDrErFrHrIrKrLrMrNrPrRrbrfrhrjrkrlrmrnrprrrtrvrxryr|twvfvtyfyt|t",
    "0.02": "77A/TYYT\\/tvtyxfxt",
    "0.025": "WW",
    "0.03": "(j[j{j",
    "0.035": "_B_D_E_F_H_I_K_L_M_N_P_R_b_h_i_k_l_m_n_p_r_|",
    "0.095": "_j",
    "0.1": "*X*YX*",
    "0.105": "*VV*Y*",
    "0.11": "*A*TA*K*L*T*",
    "0.145": "!*$*%*&**!*$*%*&*0*1*2*3*4*5*6*7*8*9*?*B*C*D*E*F*G*H*I*J*K*L*M*N*O*P*Q*R*S*U*W*Z*|0*1*2*3*4*5*6*7*8*9*?*B*C*D*E*F*G*H*I*J*M*N*O*P*Q*R*S*U*W*Z*|*",
  }
