/**
 * AC3 — one font family's advance widths for the layout oracle (`tableMetrics`), generated by
 * `tools/layout-report/calibrate/font-widths.js` from the browser. Pure data.
 */
export interface FaceMetrics {
  /** Registry key, e.g. `'fraunces'` (`FontRef.metricsKey`). */
  key: string
  /** CSS family names that resolve to this face (canonical first, then the fontsource name). */
  families: string[]
  /** The CSS generic family the stack ends with. */
  generic: 'serif' | 'sans-serif' | 'monospace' | 'cursive'
  /** Advance of a glyph with no entry and no NFD base letter (the a-z average, em). */
  fallback: number
  /** Weight 400 advances (em, no letter-spacing). */
  regular: Record<string, number>
  /** Weight 700 advances (em), used for bold runs. */
  bold: Record<string, number>
}
