/**
 * AC3 — one font family's advance widths for the layout oracle (`tableMetrics`), generated by
 * `tools/layout-report/calibrate/font-widths.js` from the browser. Pure data.
 */
export interface FaceMetrics {
  /** Registry key, e.g. `'fraunces'` (`FontRef.metricsKey`). */
  key: string
  /** CSS family names that resolve to this face (canonical first, then the fontsource name). */
  families: string[]
  /** The CSS generic family the stack ends with. */
  generic: 'serif' | 'sans-serif' | 'monospace' | 'cursive'
  /** Advance of a glyph with no entry and no NFD base letter (the a-z average, em). */
  fallback: number
  /** Weight 400 advances (em, no letter-spacing). */
  regular: Record<string, number>
  /** Weight 700 advances (em), used for bold runs. */
  bold: Record<string, number>
  /** Kerning pairs (em, added to the second glyph's advance), grouped by value:
   *  `{ "-0.075": "TaTeTo…" }` — each two characters of a string are one pair. Measured at 400,
   *  used for bold too. Absent = no kerning (the face has none, or it was not measured). */
  kern?: Record<string, string>
}
